# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            tagspace.me
tagline:          home
url:              http://tagspace.me
paginate:         1
baseurl:          /
author:
  name:           Anne Celestino
  url:            https://twitter.com/hubwub
  email:          hubwub@tagspace.me

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/hubwub/hubwub.github.io

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
